import { camel, getSupabase } from "../../../db/supabase";
import { INCOME_CATEGORIES, TRANSACTION_CATEGORIES } from "../../categories";
type Payload={kind?:"expense"|"income";description?:string;category?:string;amountCents?:number;occurredOn?:string;source?:"manual"|"assistant"};
const validDate=(v:string)=>/^\d{4}-\d{2}-\d{2}$/.test(v);
function validate(p:Payload){const description=p.description?.trim()??"",amount=Math.round(Number(p.amountCents)),date=p.occurredOn??"",category=p.category?.trim()||"";if(!["expense","income"].includes(p.kind??""))return{error:"Tipo inválido."};const allowed=p.kind==="income"?INCOME_CATEGORIES:TRANSACTION_CATEGORIES;if(!allowed.includes(category as never))return{error:`Categoria inválida para ${p.kind==="income"?"receita":"despesa"}.`};if(!description||description.length>120)return{error:"Informe uma descrição de até 120 caracteres."};if(!Number.isSafeInteger(amount)||amount<=0)return{error:"Informe um valor válido."};if(!validDate(date))return{error:"Informe uma data válida."};return{data:{kind:p.kind,description,category,amount_cents:amount,occurred_on:date,source:p.source==="assistant"?"assistant":"manual"}}}
export async function GET(){try{const{data,error}=await getSupabase().from("transactions").select("*").is("deleted_at",null).order("occurred_on",{ascending:false}).order("id",{ascending:false}).limit(200);if(error)throw error;return Response.json({transactions:(data??[]).map(r=>camel(r))})}catch(e){return Response.json({error:e instanceof Error?e.message:"Não foi possível carregar os lançamentos."},{status:500})}}
export async function POST(req:Request){try{const c=validate(await req.json());if("error"in c)return Response.json({error:c.error},{status:400});const{data,error}=await getSupabase().from("transactions").insert(c.data).select().single();if(error)throw error;return Response.json({transaction:camel(data)},{status:201})}catch(e){return Response.json({error:e instanceof Error?e.message:"Não foi possível criar o lançamento."},{status:500})}}
export async function PATCH(req:Request){try{const p=await req.json() as Payload&{id?:number},id=Math.round(Number(p.id)),c=validate(p);if(!Number.isSafeInteger(id)||id<=0)return Response.json({error:"Lançamento inválido."},{status:400});if("error"in c)return Response.json({error:c.error},{status:400});const{data,error}=await getSupabase().from("transactions").update({...c.data,updated_at:new Date().toISOString()}).eq("id",id).is("deleted_at",null).select().single();if(error)throw error;return Response.json({transaction:camel(data)})}catch(e){return Response.json({error:e instanceof Error?e.message:"Não foi possível editar."},{status:500})}}
export async function DELETE(req:Request){try{const id=Math.round(Number(new URL(req.url).searchParams.get("id")));const{error}=await getSupabase().from("transactions").update({deleted_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",id).is("deleted_at",null);if(error)throw error;return Response.json({deleted:true,id})}catch(e){return Response.json({error:e instanceof Error?e.message:"Não foi possível excluir."},{status:500})}}
