"use client";
import { useEffect, useMemo, useState } from "react";
import { TRANSACTION_CATEGORIES } from "./categories";
type Card={id:number;name:string;bank:string;lastFour:string;creditLimitCents:number;closingDay:number;dueDay:number;color:string};
type Invoice={id:number;cardId:number;referenceMonth:string;status:"open"|"paid";totalCents:number};
type Debt={id:number;cardId:number;description:string;category:string;totalCents:number;installmentCount:number;paidInstallments:number;paidCents:number;installmentCents:number};
type Data={cards:Card[];invoices:Invoice[];debts:Debt[]};
const money=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v/100);
const today=()=>new Date().toLocaleDateString("en-CA",{timeZone:"America/Sao_Paulo"});
const emptyCard={name:"",bank:"",lastFour:"",creditLimit:"",closingDay:"10",dueDay:"17",color:"green"};
const emptyPurchase={cardId:"",description:"",category:"Outros",purchaseDate:today(),total:"",installmentCount:"1"};
export default function CardsView({mode,onNotice}:{mode:"cards"|"debts";onNotice:(m:string)=>void}){
 const[data,setData]=useState<Data>({cards:[],invoices:[],debts:[]});const[cardModal,setCardModal]=useState(false),[purchaseModal,setPurchaseModal]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);const[card,setCard]=useState(emptyCard),[purchase,setPurchase]=useState(emptyPurchase);
 const cardMap=useMemo(()=>Object.fromEntries(data.cards.map(c=>[c.id,c])),[data.cards]);
 async function load(){try{const r=await fetch("/api/cards",{cache:"no-store"}),b=await r.json();if(!r.ok)throw new Error(b.error);setData(b)}catch(e){onNotice(e instanceof Error?e.message:"Não foi possível carregar.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function createCard(){setSaving(true);try{const creditLimitCents=Math.round(Number(card.creditLimit.replace(".","").replace(",","."))*100),r=await fetch("/api/cards",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"create_card",...card,creditLimitCents})}),b=await r.json();if(!r.ok)throw new Error(b.error);setCardModal(false);setCard(emptyCard);await load();onNotice("Cartão cadastrado.")}catch(e){onNotice(e instanceof Error?e.message:"Não foi possível salvar.")}finally{setSaving(false)}}
 async function createPurchase(){setSaving(true);try{const totalCents=Math.round(Number(purchase.total.replace(".","").replace(",","."))*100),r=await fetch("/api/cards",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"create_purchase",...purchase,cardId:Number(purchase.cardId),totalCents,installmentCount:Number(purchase.installmentCount)})}),b=await r.json();if(!r.ok)throw new Error(b.error);setPurchaseModal(false);setPurchase(emptyPurchase);await load();onNotice(Number(purchase.installmentCount)>1?"Compra adicionada às Dívidas.":"Compra adicionada à fatura.")}catch(e){onNotice(e instanceof Error?e.message:"Não foi possível salvar.")}finally{setSaving(false)}}
 async function pay(i:Invoice){if(!confirm(`Marcar a fatura de ${i.referenceMonth} como paga?`))return;const r=await fetch("/api/cards",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:"pay_invoice",invoiceId:i.id})});if(r.ok){await load();onNotice("Fatura paga. Dívidas atualizadas automaticamente.")}}
 function purchaseForm(){return <div className="modal-backdrop"><div className="modal"><button className="modal-close" onClick={()=>setPurchaseModal(false)}>×</button><p className="eyebrow">NOVA COMPRA</p><h2>Adicionar à fatura</h2><label>Cartão<select value={purchase.cardId} onChange={e=>setPurchase({...purchase,cardId:e.target.value})}><option value="">Selecione</option>{data.cards.map(c=><option key={c.id} value={c.id}>{c.name} · {c.lastFour}</option>)}</select></label><label>Descrição<input value={purchase.description} onChange={e=>setPurchase({...purchase,description:e.target.value})}/></label><div className="field-row"><label>Valor total<input inputMode="decimal" value={purchase.total} onChange={e=>setPurchase({...purchase,total:e.target.value})}/></label><label>Data<input type="date" value={purchase.purchaseDate} onChange={e=>setPurchase({...purchase,purchaseDate:e.target.value})}/></label></div><div className="field-row"><label>Categoria<select value={purchase.category} onChange={e=>setPurchase({...purchase,category:e.target.value})}>{TRANSACTION_CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></label><label>Parcelas<input type="number" min="1" max="60" value={purchase.installmentCount} onChange={e=>setPurchase({...purchase,installmentCount:e.target.value})}/></label></div><button className="primary wide" disabled={saving} onClick={()=>void createPurchase()}>Adicionar compra</button></div></div>}
 if(loading)return <div className="agenda-empty">Carregando…</div>;
 if(mode==="debts")return <><div className="agenda-toolbar"><div><p className="eyebrow">PARCELAMENTOS</p><h2>Minhas Dívidas</h2></div><button className="primary" disabled={!data.cards.length} onClick={()=>setPurchaseModal(true)}>＋ Nova compra</button></div><div className="debt-grid">{data.debts.length?data.debts.map(d=>{const pct=Math.round(d.paidInstallments/d.installmentCount*100);return <article className="debt-card" key={d.id}><div className="debt-head"><div><small>{cardMap[d.cardId]?.name} · {d.category}</small><h3>{d.description}</h3></div><strong>{d.paidInstallments}/{d.installmentCount}</strong></div><div className="progress"><i style={{width:`${pct}%`}}/></div><div className="debt-stats"><span>Saldo devedor<strong>{money(d.totalCents-d.paidCents)}</strong></span><span>Total pago<strong>{money(d.paidCents)}</strong></span><span>Valor parcela<strong>{money(d.installmentCents)}</strong></span></div></article>}):<div className="agenda-empty"><strong>Nenhuma dívida parcelada.</strong><small>Compras em mais de 1x aparecerão aqui.</small></div>}</div>{purchaseModal&&purchaseForm()}</>;
 return <><div className="agenda-toolbar"><div><p className="eyebrow">CRÉDITO</p><h2>Cartões e Faturas</h2></div><div className="agenda-tools"><button onClick={()=>setCardModal(true)}>＋ Cadastrar cartão</button><button className="primary" disabled={!data.cards.length} onClick={()=>setPurchaseModal(true)}>＋ Nova compra</button></div></div>{!data.cards.length?<div className="agenda-empty"><strong>Cadastre seu primeiro cartão.</strong><small>Informe limite, fechamento e vencimento.</small><button onClick={()=>setCardModal(true)}>Cadastrar cartão</button></div>:<div className="cards-grid">{data.cards.map(c=>{const open=data.invoices.filter(i=>i.cardId===c.id&&i.status==="open").reduce((s,i)=>s+i.totalCents,0);return <article className={`credit-card ${c.color}`} key={c.id}><small>{c.bank}</small><h3>{c.name}</h3><p>•••• {c.lastFour}</p><div><span>Limite disponível<strong>{money(Math.max(0,c.creditLimitCents-open))}</strong></span><span>Fecha dia {c.closingDay}<strong>Vence dia {c.dueDay}</strong></span></div></article>})}</div>}<div className="section-title"><div><p className="eyebrow">FATURAS</p><h3>Histórico e próximas</h3></div></div><div className="invoice-list">{data.invoices.filter(i=>i.totalCents>0).map(i=><article key={i.id}><div><small>{cardMap[i.cardId]?.name}</small><strong>{i.referenceMonth}</strong></div><b>{money(i.totalCents)}</b><span className={i.status}>{i.status==="paid"?"Paga":"Aberta"}</span>{i.status==="open"&&<button onClick={()=>void pay(i)}>Marcar como paga</button>}</article>)}</div>{cardModal&&<div className="modal-backdrop"><div className="modal"><button className="modal-close" onClick={()=>setCardModal(false)}>×</button><p className="eyebrow">NOVO CARTÃO</p><h2>Dados do cartão</h2><label>Apelido<input value={card.name} onChange={e=>setCard({...card,name:e.target.value})} placeholder="Ex.: Nubank principal"/></label><div className="field-row"><label>Banco<input value={card.bank} onChange={e=>setCard({...card,bank:e.target.value})}/></label><label>Últimos 4 dígitos<input inputMode="numeric" maxLength={4} value={card.lastFour} onChange={e=>setCard({...card,lastFour:e.target.value})}/></label></div><label>Limite<input inputMode="decimal" value={card.creditLimit} onChange={e=>setCard({...card,creditLimit:e.target.value})}/></label><div className="field-row"><label>Dia de fechamento<input type="number" min="1" max="28" value={card.closingDay} onChange={e=>setCard({...card,closingDay:e.target.value})}/></label><label>Dia de vencimento<input type="number" min="1" max="28" value={card.dueDay} onChange={e=>setCard({...card,dueDay:e.target.value})}/></label></div><button className="primary wide" disabled={saving} onClick={()=>void createCard()}>Cadastrar cartão</button></div></div>}{purchaseModal&&purchaseForm()}</>
}
