create table if not exists public.recurring_rules (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('expense','income')),
  description text not null,
  category text not null,
  amount_cents integer not null check (amount_cents > 0),
  day_of_month integer not null check (day_of_month between 1 and 28),
  start_month text not null,
  end_month text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.transactions add column if not exists status text not null default 'settled';
alter table public.transactions add column if not exists recurring_rule_id bigint references public.recurring_rules(id);
alter table public.transactions add column if not exists invoice_id bigint references public.card_invoices(id);
alter table public.transactions drop constraint if exists transactions_status_check;
alter table public.transactions add constraint transactions_status_check check (status in ('pending','settled'));
drop index if exists public.idx_transactions_recurring_date;
drop index if exists public.idx_transactions_invoice;
create unique index idx_transactions_recurring_date on public.transactions(recurring_rule_id,occurred_on);
create unique index idx_transactions_invoice on public.transactions(invoice_id);
create index if not exists idx_transactions_month_status on public.transactions(occurred_on,status);

alter table public.recurring_rules enable row level security;
revoke all on public.recurring_rules from anon, authenticated;
grant all on public.recurring_rules to service_role;
grant usage, select on sequence public.recurring_rules_id_seq to service_role;
