create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('expense','income')),
  description text not null,
  category text not null default 'Outros',
  amount_cents integer not null check (amount_cents > 0),
  occurred_on date not null,
  source text not null default 'manual' check (source in ('manual','assistant')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);
create index if not exists idx_transactions_occurred_on on public.transactions(occurred_on);
create index if not exists idx_transactions_category_date on public.transactions(category,occurred_on);

create table if not exists public.calendar_events (
  id bigint generated by default as identity primary key,
  title text not null,
  event_date date not null,
  start_time time,
  end_time time,
  location text,
  notes text,
  color text not null default 'green',
  status text not null default 'scheduled' check (status in ('scheduled','completed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);
create index if not exists idx_calendar_events_date_status on public.calendar_events(event_date,status);

create table if not exists public.credit_cards (
  id bigint generated by default as identity primary key,
  name text not null, bank text not null, last_four text not null,
  credit_limit_cents integer not null check (credit_limit_cents > 0),
  closing_day integer not null check (closing_day between 1 and 28),
  due_day integer not null check (due_day between 1 and 28),
  color text not null default 'green',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table if not exists public.card_purchases (
  id bigint generated by default as identity primary key,
  card_id bigint not null references public.credit_cards(id),
  description text not null, category text not null default 'Outros',
  purchase_date date not null, total_cents integer not null check (total_cents > 0),
  installment_count integer not null default 1 check (installment_count between 1 and 60),
  created_at timestamptz not null default now(), deleted_at timestamptz
);
create index if not exists idx_card_purchases_card_date on public.card_purchases(card_id,purchase_date);

create table if not exists public.card_installments (
  id bigint generated by default as identity primary key,
  purchase_id bigint not null references public.card_purchases(id),
  card_id bigint not null references public.credit_cards(id),
  installment_number integer not null, amount_cents integer not null,
  invoice_month text not null, status text not null default 'pending' check (status in ('pending','paid')),
  paid_at timestamptz
);
create index if not exists idx_card_installments_invoice on public.card_installments(card_id,invoice_month);
create index if not exists idx_card_installments_purchase on public.card_installments(purchase_id);

create table if not exists public.card_invoices (
  id bigint generated by default as identity primary key,
  card_id bigint not null references public.credit_cards(id),
  reference_month text not null, status text not null default 'open' check (status in ('open','paid')),
  paid_at timestamptz, unique(card_id,reference_month)
);
create index if not exists idx_card_invoices_card_month on public.card_invoices(card_id,reference_month);

alter table public.transactions enable row level security;
alter table public.calendar_events enable row level security;
alter table public.credit_cards enable row level security;
alter table public.card_purchases enable row level security;
alter table public.card_installments enable row level security;
alter table public.card_invoices enable row level security;

revoke all on all tables in schema public from anon, authenticated;
grant all on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;
