alter table public.transactions add column if not exists legacy_id text;
alter table public.credit_cards add column if not exists legacy_id text;
alter table public.card_purchases add column if not exists legacy_id text;

create unique index if not exists idx_transactions_legacy_id
  on public.transactions(legacy_id) where legacy_id is not null;
create unique index if not exists idx_credit_cards_legacy_id
  on public.credit_cards(legacy_id) where legacy_id is not null;
create unique index if not exists idx_card_purchases_legacy_id
  on public.card_purchases(legacy_id) where legacy_id is not null;
create unique index if not exists idx_card_installments_purchase_number
  on public.card_installments(purchase_id, installment_number);

create table if not exists public.category_budgets (
  id bigint generated by default as identity primary key,
  category text not null unique,
  limit_cents integer not null check (limit_cents >= 0),
  legacy_id text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.category_budgets enable row level security;
revoke all on public.category_budgets from anon, authenticated;
grant all on public.category_budgets to service_role;
grant usage, select on sequence public.category_budgets_id_seq to service_role;
